version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: e_commerce_platform.settings
      PYTHONUNBUFFERED: 1
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    command: pytest --cov=.
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: e_commerce_platform.settings
      python_files : tests.py test_*.py *_tests.py
    depends_on:
      - db
 